package com.twl.xg.domain;

import java.util.ArrayList;
import java.util.List;

/**
 * This is the wrapper class for the whole sensor data package. The sensor data in response
 * body for the request is generated by converting this object to JSON.
 *
 * @see com.twl.xg.controller.DataController
 * @author Xiaozheng Guo
 * @version 1.0
 */
public class DataPackage {
  private int size;
  private List<BorderRouterWrapper> borderRouterWrapperList;

  public DataPackage(List<BorderRouterWrapper> borderRouterWrapperList) {
    if (borderRouterWrapperList == null) {
      size = 0;
      return;
    }
    this.borderRouterWrapperList = new ArrayList<>(borderRouterWrapperList);
    for (BorderRouterWrapper borderRouterWrapper : borderRouterWrapperList) {
      size += borderRouterWrapper.getSize();
    }
  }

  public int getSize() {
    return size;
  }

  public List<BorderRouterWrapper> getBorderRouterWrapperList() {
    return borderRouterWrapperList;
  }
}
