
<html>
<title>XG proj</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body, h1,h2,h3,h4,h5,h6 {font-family: "Montserrat", sans-serif}
    .w3-row-padding img {margin-bottom: 12px}
    .bgimg {
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        background-image: url('https://diginomica.com/wp-content/uploads/2015/09/Fotolia_88452577_Subscription_Monthly_M.jpg');
        min-height: 100%;
    }

</style>
<body>

<!-- Sidebar with image -->
<nav class="w3-sidebar w3-hide-medium w3-hide-small" style="width:40%">
    <div class="bgimg"></div>
</nav>

<!-- Hidden Sidebar (reveals when clicked on menu icon)-->
<nav class="w3-sidebar w3-black w3-animate-right w3-xxlarge" style="display:none;padding-top:150px;right:0;z-index:2" id="mySidebar">
    <a href="javascript:void(0)" onclick="closeNav()" class="w3-button w3-black w3-xxxlarge w3-display-topright" style="padding:0 12px;">
        <i class="fa fa-remove"></i>
    </a>
    <div class="w3-bar-block w3-center">
        <a href="#" class="w3-bar-item w3-button w3-text-grey w3-hover-black" onclick="closeNav()">Home</a>
        <a href="#portfolio" class="w3-bar-item w3-button w3-text-grey w3-hover-black" onclick="closeNav()">Portfolio</a>
        <a href="#about" class="w3-bar-item w3-button w3-text-grey w3-hover-black" onclick="closeNav()">About</a>
        <a href="#contact" class="w3-bar-item w3-button w3-text-grey w3-hover-black" onclick="closeNav()">Contact</a>
    </div>
</nav>

<!-- Page Content -->
<div class="w3-main w3-padding-large" style="margin-left:40%">

    <!-- Menu icon to open sidebar -->
    <span class="w3-button w3-top w3-white w3-xxlarge w3-text-grey w3-hover-text-black" style="width:auto;right:0;" onclick="openNav()"><i class="fa fa-bars"></i></span>

    <!-- Header -->
    <header class="w3-container w3-center" style="padding:128px 16px" id="home">
        <h1 class="w3-jumbo"><b>House Monitor</b></h1>
        <p>An IoT webserver || from data to data.</p>
        <!--   <img src="/w3images/profile_girl.jpg" class="w3-image w3-hide-large w3-hide-small w3-round" style="display:block;width:60%;margin:auto;">
          <img src="/w3images/profile_girl.jpg" class="w3-image w3-hide-large w3-hide-medium w3-round" width="1000" height="1333">
          <button class="w3-button w3-light-grey w3-padding-large w3-margin-top">
            <i class="fa fa-download"></i> Download Resume
          </button> -->
    </header>

    <!-- Portfolio Section -->
    <div class="w3-padding-32 w3-content" id="portfolio">
        <h2 class="w3-text-grey"> </h2>
        <hr class="w3-opacity">

        <!-- Grid for photos -->
        <div class="w3-row-padding" style="margin:0 -16px">
            <div class="w3-half">
                <img src="https://www.sensorsexpo.com/sites/sensorsexpo/files/til_image/iotecosystem_icon_final_0.png" style="width:100%">
                <img src="https://mscorpmedia.azureedge.net/mscorpmedia/2017/09/IoT-The-Intelligent-CLoud-expohero.jpg" style="width:100%">
                <img src="https://www.360logica.com/blog/wp-content/uploads/2017/07/IOT-2.png" style="width:100%">
            </div>

            <div class="w3-half">
                <img src="https://www.farnetworks.com/wp-content/uploads/2016/05/iot-data-mining.jpg" style="width:100%">
                <img src="https://www.farnetworks.com/wp-content/uploads/2016/05/iot-security1.png" style="width:100%">
                <img src="https://www.farnetworks.com/wp-content/uploads/2016/05/iot-building-automation.png" style="width:100%">
                <!--  <img src="/w3images/p6.jpg" style="width:100%"> -->
            </div>
            <!-- End photo grid -->
        </div>
        <!-- End Portfolio Section -->
    </div>

    <!-- About Section -->
    <div class="w3-content w3-justify w3-text-grey w3-padding-32" id="about">
        <h2>About</h2>
        <hr class="w3-opacity">
        <p> This website is created for XG's graduate project, a web-server for the 6LowPan IoT platform.
            Clients can view the data generated by a group of small home sensors by putting their border-router ipv6 address or simply clicking the function button.
            Our project is currently under construction. will be coming soon.
        </p>
        <h3 class="w3-padding-16">Our Progress</h3>
        <p class="w3-wide">Coap Communication</p>
        <div class="w3-light-grey">
            <div class="w3-container w3-center w3-padding-small w3-dark-grey" style="width:35%">35%</div>
        </div>
        <p class="w3-wide">Web Front-end Design</p>
        <div class="w3-light-grey">
            <div class="w3-container w3-center w3-padding-small w3-dark-grey" style="width:25%">25%</div>
        </div>
        <p class="w3-wide">Web Back-end Design</p>
        <div class="w3-light-grey">
            <div class="w3-container w3-center w3-padding-small w3-dark-grey" style="width:15%">15%</div>
        </div><br>

        <!-- Contact Section -->
        <div class="w3-padding-32 w3-content w3-text-grey" id="contact" style="margin-bottom:64px">
            <h2>Contact Us</h2>
            <hr class="w3-opacity">

            <div class="w3-section">
                <p><i class="fa fa-map-marker fa-fw w3-xxlarge w3-margin-right"></i> Location:
                <li>Boston, MA, US</li>
                </p>
                <p><i class="fa fa-phone fa-fw w3-xxlarge w3-margin-right"></i> Phone:
                <li> elfie: +1(781)6588555 </li>
                <li> Will: +1(781)5395213</li>
                </p>
                <p><i class="fa fa-envelope fa-fw w3-xxlarge w3-margin-right"> </i>Email:
                <li> Will: xguo.tufts@gmail.com</li>
                <li> Elfie: elfiegxf@gmail.com</li>
                </p>
            </div>

            <!-- Google Map -->
            <div id="googleMap" class="w3-greyscale-max" style="width:100%;height:300px;margin:36px 0;"></div>

            <p>Lets get in touch. Send us a message:</p>
            <form action="/action_page.php" target="_blank">
                <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Name" required name="Name"></p>
                <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Email" required name="Email"></p>
                <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Subject" required name="Subject"></p>
                <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Message" required name="Message"></p>
                <p>
                    <button class="w3-button w3-light-grey w3-padding-large" type="submit">
                        <i class="fa fa-paper-plane"></i> SEND MESSAGE
                    </button>
                </p>
            </form>
            <!-- End Contact Section -->
        </div>

        <!-- Footer -->
        <footer class="w3-container w3-padding-64 w3-light-grey w3-center w3-opacity w3-xlarge" style="margin:-24px">
            <i class="fa fa-facebook-official w3-hover-opacity"></i>
            <i class="fa fa-instagram w3-hover-opacity"></i>
            <i class="fa fa-snapchat w3-hover-opacity"></i>
            <i class="fa fa-pinterest-p w3-hover-opacity"></i>
            <i class="fa fa-twitter w3-hover-opacity"></i>
            <i class="fa fa-linkedin w3-hover-opacity"></i>
            <p class="w3-medium">Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">TWL XG's Group</a></p>
            <!-- End footer -->
        </footer>

        <!-- END PAGE CONTENT -->
    </div>

    <!-- Add Google Maps -->
    <script>
        function myMap()
        {
            myCenter=new google.maps.LatLng(42.3601, -71.0589);
            var mapOptions= {
                center:myCenter,
                zoom:12, scrollwheel: true, draggable: true,
                mapTypeId:'roadmap'

            };
            var map=new google.maps.Map(document.getElementById("googleMap"),mapOptions);

            var marker = new google.maps.Marker({
                position: myCenter,
                map : map
            });
        }

        // Open and close sidebar
        function openNav() {
            document.getElementById("mySidebar").style.width = "60%";
            document.getElementById("mySidebar").style.display = "block";
        }

        function closeNav() {
            document.getElementById("mySidebar").style.display = "none";
        }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDiEtFIhixoY8j7lnDIAzKy2yj_RnF2UEM&callback=myMap"></script>
    <!--
    template credits to: https://www.w3schools.com
    -->

</body>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap">
</script>
